"""
Django settings for meinprojekt project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import configparser

# BASE_DIR zeigt auf das Hauptverzeichnis deines Projekts
BASE_DIR = Path(__file__).resolve().parent.parent

config = configparser.RawConfigParser()
init_path = os.path.join(BASE_DIR, 'meinprojekt', 'secret.ini')
config.read(init_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!:
# SECRET_KEY = config['Server']['key']
SECRET_KEY = config['evar']['key']

# SECURITY WARNING: don't run with debug turned on in production!
# ALLOWED_HOSTS = ['*']
# for test
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']
# for server
# ALLOWED_HOSTS = ['analyttest.data.heise.de', 'localhost', '127.0.0.1', '2a00:e68:14:1c:d6be:d9ff:fefb:ae05']
# ALLOWED_HOSTS = ['2a00:e68:14:1c:d6be:d9ff:fefb:ae05', 'analyttest.data.heise.de', 'localhost']

# SECURE_HSTS_INCLUDE_SUBDOMAINS=False
# SECURE_HSTS_SECONDS=518400

# SESSION_COOKIE_SECURE=True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'eingabemaske.apps.EingabemaskeConfig',
    'planung.apps.PlanungConfig',  # Neue App hinzufügen
    'sales_prognosen_matrix',
    'aldjemy',  # Für SQLAlchemy-Integration mit Django-Modellen
    'django_select2',
    'shared_fields',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'meinprojekt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'shared_templates' / 'templates',  # for base.html
            BASE_DIR / 'sales_prognosen_matrix/templates',  # for sales_objekt
        ],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'meinprojekt.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_DIR = os.path.join(BASE_DIR, 'my_static')

STATICFILES_DIRS = [STATIC_DIR]
# print("STATIC_DIR: ", STATIC_DIR)

STATIC_URL = 'static/'
STATIC_ROOT = 'http://127.0.0.1:8000/django/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# print("STATIC_ROOT: ", STATIC_ROOT)

DEBUG = True
# for run in server
# DEBUG = False


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
